/**
 * Code generator for route files
 */

import { defaultConfig } from "./config";
import { PACKAGE_NAME } from "./constants";
import { pascalCase, wrapDoubleQuotes } from "./string";
import { RouteConfig, RouteNode } from "./types";

/**
 * Generate TypeScript code for route structure constant
 */
const generateStructureCode = (structure: RouteNode, indent: number = 2): string => {
  const indentStr = " ".repeat(indent);
  const lines: string[] = [];

  // Sort entries to put $param and $route first
  const entries = Object.entries(structure);
  const metadataEntries = entries.filter(([key]) => key.startsWith("$"));
  const regularEntries = entries.filter(([key]) => !key.startsWith("$"));
  const sortedEntries = [...metadataEntries, ...regularEntries];

  for (const [key, value] of sortedEntries) {
    // Check if key needs to be quoted (contains special characters)
    const needsQuotes = /[^a-zA-Z0-9_$]/.test(key);
    const quotedKey = needsQuotes ? wrapDoubleQuotes(key) : key;

    switch (typeof value) {
      case "object":
        if (value !== null) {
          const childLines = generateStructureCode(value, indent + 2);
          if (childLines) {
            lines.push(`${indentStr}${quotedKey}: {`);
            lines.push(childLines);
            lines.push(`${indentStr}},`);
          }
        }
        break;

      case "boolean":
        lines.push(`${indentStr}${quotedKey}: ${value},`);
        break;

      case "string":
        lines.push(`${indentStr}${quotedKey}: ${wrapDoubleQuotes(value)},`);
        break;
    }
  }

  return lines.join("\n");
};

/**
 * Generate complete route file content
 */
export const generateRouteFile = (structure: RouteNode, config: RouteConfig): string => {
  const structureCode = generateStructureCode(structure);
  const basePrefix = config.basePrefix ?? "";
  const customImports = config.imports?.join("\n") ?? "";
  const routesName = config.routesName ?? defaultConfig.routesName;
  const structureName = routesName.toUpperCase();
  const typeName = pascalCase(routesName);

  // Generate paramTypeMap import or default to empty object
  const paramTypeMapImport = config.paramTypeMap
    ? `import type { ${config.paramTypeMap.type} } from "${config.paramTypeMap.from}";`
    : "";
  const paramTypeMapType = config.paramTypeMap ? config.paramTypeMap.type : "{}";

  return `/**
 * Auto-generated Next.js route builder
 * Generated from: ${config.input}
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated
 */

import { createRouteBuilder, RouteBuilderObject } from "${PACKAGE_NAME}";
${paramTypeMapImport ? paramTypeMapImport + "\n" : ""}${customImports ? customImports + "\n" : ""}
// Route structure definition
const ${structureName} = {
${structureCode}
} as const;

// Type-safe route builder with parameter types
export type ${typeName} = RouteBuilderObject<typeof ${structureName}, ${paramTypeMapType}>;

// Route builder instance
export const ${routesName} = createRouteBuilder<typeof ${structureName}, ${paramTypeMapType}>(${structureName}, [], "${basePrefix}");
`;
};
