/**
 * Code generator for route files
 */

import { RouteNode, RouteConfig } from "./types";
import { PACKAGE_NAME } from "./constants";

/**
 * Generate TypeScript code for route structure constant
 */
const generateStructureCode = (structure: RouteNode, indent: number = 2): string => {
  const indentStr = " ".repeat(indent);
  const lines: string[] = [];

  // Sort entries to put $param and $route first
  const entries = Object.entries(structure);
  const metadataEntries = entries.filter(([key]) => key.startsWith("$"));
  const regularEntries = entries.filter(([key]) => !key.startsWith("$"));
  const sortedEntries = [...metadataEntries, ...regularEntries];

  for (const [key, value] of sortedEntries) {
    // Check if key needs to be quoted (contains special characters)
    const needsQuotes = /[^a-zA-Z0-9_$]/.test(key);
    const quotedKey = needsQuotes ? `"${key}"` : key;

    if (typeof value === "object" && value !== null) {
      const childLines = generateStructureCode(value, indent + 2);
      if (childLines) {
        lines.push(`${indentStr}${quotedKey}: {`);
        lines.push(childLines);
        lines.push(`${indentStr}},`);
      }
    } else if (typeof value === "boolean") {
      lines.push(`${indentStr}${quotedKey}: ${value},`);
    } else if (typeof value === "string") {
      lines.push(`${indentStr}${quotedKey}: "${value}",`);
    }
  }

  return lines.join("\n");
};

/**
 * Generate parameter type map from config
 */
const generateParamTypeMap = (paramTypes?: Record<string, string>): string => {
  if (!paramTypes || Object.keys(paramTypes).length === 0) {
    return "{}";
  }

  const entries = Object.entries(paramTypes).map(([key, type]) => `  ${key}: ${type};`);
  return `{\n${entries.join("\n")}\n}`;
};

/**
 * Generate complete route file content
 */
export const generateRouteFile = (structure: RouteNode, config: RouteConfig): string => {
  const structureCode = generateStructureCode(structure);
  const paramTypeMap = generateParamTypeMap(config.paramTypes);
  const basePrefix = config.basePrefix || "";
  const customImports = config.imports?.join("\n") || "";

  return `/**
 * Auto-generated Next.js route builder
 * Generated from: ${config.input}
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated
 */

import { createRouteBuilder, RouteBuilderObject } from "${PACKAGE_NAME}";
${customImports ? "\n" + customImports + "\n" : ""}
// Route structure definition
const ROUTE_STRUCTURE = {
${structureCode}
} as const;

// Parameter type mappings
type ParamTypeMap = ${paramTypeMap};

// Type-safe route builder with parameter types
export type Routes = RouteBuilderObject<typeof ROUTE_STRUCTURE, ParamTypeMap>;

// Route builder instance
export const routes = createRouteBuilder(ROUTE_STRUCTURE, [], "${basePrefix}") as Routes;
`;
};
